// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGz8zDDpPrHLWHoxCcGPZHl-x2MLAqMWI',
    appId: '1:512121070896:android:07aeb7682423d491d954f5',
    messagingSenderId: '512121070896',
    projectId: 'fall-detection-ed1a9',
    databaseURL: 'https://fall-detection-ed1a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fall-detection-ed1a9.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiAunnABfV2T6BUKaakzabCNF5WkNKh50',
    appId: '1:512121070896:web:d2da7073047c4c79d954f5',
    messagingSenderId: '512121070896',
    projectId: 'fall-detection-ed1a9',
    authDomain: 'fall-detection-ed1a9.firebaseapp.com',
    databaseURL: 'https://fall-detection-ed1a9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fall-detection-ed1a9.firebasestorage.app',
    measurementId: 'G-26LHLF6JHZ',
  );
}
